version: "3.9"
services:
  manulife:
    container_name: manulife
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_PROD=mongodb://manulife-mongo:27017/manulife_prod
      - REDIS_URL=redis://manulife-redis:6379
    build: .
    ports:
      - 3000
    links:
      - redis
      - mongo
  mongo:
    container_name: manulife-mongo
    image: "mongo:latest"
    ports:
      - "27017:27017"
  redis:
    container_name: manulife-redis
    image: "redis:7.0-rc"
